### Developer: Edgar Moises Hernandez-Gonzalez
### pandas merge

In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame([
    ["12", 3],
    ["13", 5],
    ["15", 8],
    ["16", 20],
    ["20", 10],
],
    columns=["id", "stock"])
df1

   id  stock
0  12      3
1  13      5
2  15      8
3  16     20
4  20     10

In [3]:
df2 = pd.DataFrame([
    ["12", "100"],
    ["16", "200"],
    ["50", "300"]
],
    columns=["id", "precio"])
df2

   id precio
0  12    100
1  16    200
2  50    300

In [4]:
# por defecto how="inner" (filas comunes)
pd.merge(df1, df2)

   id  stock precio
0  12      3    100
1  16     20    200

In [5]:
pd.merge(df1, df2, how="outer")

   id  stock precio
0  12    3.0    100
1  13    5.0    NaN
2  15    8.0    NaN
3  16   20.0    200
4  20   10.0    NaN
5  50    NaN    300

### varias columnas

In [6]:
df1 = pd.DataFrame([
    ["enero", "pan", 100],
    ["enero", "galletas", 50],
    ["febrero", "pan", 20],
    ["febrero", "galletas", 10]
],
    columns=["mes", "producto", "stock"])
df1

       mes  producto  stock
0    enero       pan    100
1    enero  galletas     50
2  febrero       pan     20
3  febrero  galletas     10

In [7]:
df2 = pd.DataFrame([
    ["enero", "pan", 4],
    ["enero", "galletas", 8],
    ["febrero", "pan", 4.5],
    ["febrero", "galletas", 9]
],
    columns=["mes", "producto", "precio"])
df2

       mes  producto  precio
0    enero       pan     4.0
1    enero  galletas     8.0
2  febrero       pan     4.5
3  febrero  galletas     9.0

In [8]:
pd.merge(df1, df2)

       mes  producto  stock  precio
0    enero       pan    100     4.0
1    enero  galletas     50     8.0
2  febrero       pan     20     4.5
3  febrero  galletas     10     9.0

### columnas con nombres diferentes

In [9]:
df1 = pd.DataFrame([
    ["pan", 3],
    ["galletas", 4],
    ["agua", 5],
    ["refresco", 6]
],
    columns=["producto", "stock"])
df1

   producto  stock
0       pan      3
1  galletas      4
2      agua      5
3  refresco      6

In [10]:
df2 = pd.DataFrame([
    ["pan", 13],
    ["galletas", 14],
    ["agua", 15]
],
    columns=["product", "precio"])
df2

    product  precio
0       pan      13
1  galletas      14
2      agua      15

In [12]:
# no existen columnas con el mismo nombre
# pd.merge(df1, df2)

In [13]:
df = pd.merge(df1, df2, left_on="producto", right_on="product")
df

   producto  stock   product  precio
0       pan      3       pan      13
1  galletas      4  galletas      14
2      agua      5      agua      15

In [14]:
df.drop(["product"], axis=1)

   producto  stock  precio
0       pan      3      13
1  galletas      4      14
2      agua      5      15