### Developer: Edgar Moises Hernandez-Gonzalez
### minimo y maximo, funciones normales y lambdas, unicos, ordenar y agrupar
### min, max, apply, unique, drop_duplicates y groupby

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# matriz 5x5 con numeros del -1 al 18 [-1,19)
matriz = np.random.randint(-1, 19, size=(5,5))
matriz

array([[14, -1,  0, 12, 11],
       [13,  3, 12, 16, 12],
       [ 3, 13, 18, 14,  9],
       [13, 11, -1,  2, 10],
       [-1, 13,  5, 11, 13]])

In [ ]:
df = pd.DataFrame(matriz, columns=["a","b","c","d","e"])
df

    a   b   c   d   e
0  14  -1   0  12  11
1  13   3  12  16  12
2   3  13  18  14   9
3  13  11  -1   2  10
4  -1  13   5  11  13

## minimo y maximo

In [ ]:
df.min()

a   -1
b   -1
c   -1
d    2
e    9
dtype: int64

In [ ]:
df["e"].min()

9

In [ ]:
df.min(axis=1)

0   -1
1    3
2    3
3   -1
4   -1
dtype: int64

In [ ]:
df.max()

a    14
b    13
c    18
d    16
e    13
dtype: int64

In [ ]:
df["e"].max()

13

In [ ]:
df.max(axis=1)

0    14
1    16
2    18
3    13
4    13
dtype: int64

## aplicar funciones

$ f(x) = 2x + 1 $

In [ ]:
def funcion(x):
    return 2 * x + 1

In [ ]:
# a todo el DataFrame
df = df.apply(funcion)
df

    a   b   c   d   e
0  29  -1   1  25  23
1  27   7  25  33  25
2   7  27  37  29  19
3  27  23  -1   5  21
4  -1  27  11  23  27

In [ ]:
# a una columna
df["b"] = df["b"].apply(funcion)
df

    a   b   c   d   e
0  29  -1   1  25  23
1  27  15  25  33  25
2   7  55  37  29  19
3  27  47  -1   5  21
4  -1  55  11  23  27

## funciones lambda

$ f(x) = x + 10 $

In [ ]:
y = lambda x: x + 10
print(y(5))

x = lambda a: a[0:3]
print(x("Funciones lambda en Python"))

15
Fun

$ f(x) = x^2 - 1 $

In [ ]:
# a una columna
df["b"] = df["b"].apply(lambda x: x * x - 1)
df

    a     b   c   d   e
0  29     0   1  25  23
1  27   224  25  33  25
2   7  3024  37  29  19
3  27  2208  -1   5  21
4  -1  3024  11  23  27

## Valores unicos y ordenarlos

In [ ]:
print(type(df["a"].unique()))
df["a"].unique()

<class 'numpy.ndarray'>

array([29, 27,  7, -1])

In [ ]:
df.drop_duplicates()

    a     b   c   d   e
0  29     0   1  25  23
1  27   224  25  33  25
2   7  3024  37  29  19
3  27  2208  -1   5  21
4  -1  3024  11  23  27

In [ ]:
df.drop_duplicates(subset = "a")

    a     b   c   d   e
0  29     0   1  25  23
1  27   224  25  33  25
2   7  3024  37  29  19
4  -1  3024  11  23  27

In [ ]:
sorted(df["a"])

[-1, 7, 27, 27, 29]

In [ ]:
sorted(df["a"].unique())

[-1, 7, 27, 29]

## Agrupar datos

In [ ]:
lista = [
         ["Cruz azul", "Mexico"],
         ["Tigres", "Mexico"],
         ["Barcelona", "España"],
         ["Real Madrid", "España"],
         ["Chelsea", "Inglaterra"],
         ["Manchester United", "Inglaterra"],
         ["Borussia Dortmund", "Alemania"],
         ["Juventus", "Italia"],
         ["Chivas", "Mexico"],
         ["Paris Saint-Germain", "Francia"],
         ["Sevilla", "España"],
         ["Olympique de Marsella", "Francia"],
         ["Boca Juniors", "Argentina"],
         ["Valencia", "España"],
         ["Liverpool", "Inglaterra"],
         ["Puebla", "Mexico"]
]
df = pd.DataFrame(lista, columns=["Equipo", "Pais"])
df

                   Equipo        Pais
0               Cruz azul      Mexico
1                  Tigres      Mexico
2               Barcelona      España
3             Real Madrid      España
4                 Chelsea  Inglaterra
5       Manchester United  Inglaterra
6       Borussia Dortmund    Alemania
7                Juventus      Italia
8                  Chivas      Mexico
9     Paris Saint-Germain     Francia
10                Sevilla      España
11  Olympique de Marsella     Francia
12           Boca Juniors   Argentina
13               Valencia      España
14              Liverpool  Inglaterra
15                 Puebla      Mexico

In [ ]:
grupo = df.groupby(["Pais"])
grupo.first()

                         Equipo
Pais
Alemania      Borussia Dortmund
Argentina          Boca Juniors
España                Barcelona
Francia     Paris Saint-Germain
Inglaterra              Chelsea
Italia                 Juventus
Mexico                Cruz azul

In [ ]:
verdularia = [
         ["Manzana", "Fruta", 20],
         ["Papa", "Verdura", 20],
         ["Mango", "Fruta", 40],
         ["Melon", "Fruta", 10],
         ["Platano", "Fruta", 20],
         ["Naranja", "Fruta", 6],
         ["Zanahoria", "Verdura", 17],
         ["Brocoli", "Verdura", 30]
]
df = pd.DataFrame(verdularia, columns=["Alimento", "Categoria", "Precio"])
df

    Alimento Categoria  Precio
0    Manzana     Fruta      20
1       Papa   Verdura      20
2      Mango     Fruta      40
3      Melon     Fruta      10
4    Platano     Fruta      20
5    Naranja     Fruta       6
6  Zanahoria   Verdura      17
7    Brocoli   Verdura      30

In [ ]:
grupo = df.groupby(["Categoria"])
grupo.first()

          Alimento  Precio
Categoria
Fruta      Manzana      20
Verdura       Papa      20

In [ ]:
grupo2 = df.groupby(["Categoria"]).mean()
grupo2

              Precio
Categoria
Fruta      19.200000
Verdura    22.333333